; This file was auto-generated by drush make
core = 7.x

api = 2
projects[] = "drupal"
; Modules
projects[] = "backup_migrate"
projects[] = "ctools"
projects[] = "colorbox"
projects[] = "devel"
projects[] = "features"
projects[] = "globalredirect"
projects[] = "jquery_update"
projects[] = "l10n_update"
projects[] = "less"
projects[] = "libraries"
projects[] = "metatag"
projects[] = "module_filter"
projects[] = "navbar"
projects[] = "strongarm"
projects[] = "token"
projects[] = "views"
projects[] = "xmlsitemap"
; Themes
projects[] = "adminimal_theme"
projects[themes][type] = "theme"
projects[themes][download][type] = "git"
projects[themes][download][url] = "u12233@thor.vps-private.net:megateh.git"
projects[themes][download][branch] = "devel"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[megatehniks][download][type] = ""
projects[megatehniks][download][url] = ""
projects[megatehniks][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[flipclock][download][type] = ""
libraries[flipclock][download][url] = ""
libraries[flipclock][directory_name] = "flipclock"
libraries[flipclock][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backbone][download][type] = ""
libraries[backbone][download][url] = ""
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[lessphp][download][type] = ""
libraries[lessphp][download][url] = ""
libraries[lessphp][directory_name] = "lessphp"
libraries[lessphp][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[modernizr][download][type] = ""
libraries[modernizr][download][url] = ""
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = ""
libraries[colorbox][download][url] = ""
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[underscore][download][type] = ""
libraries[underscore][download][url] = ""
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"

