; This file was auto-generated by drush make
core = 7.x

api = 2
projects[] = "drupal"
; Modules
projects[] = "backup_migrate"
projects[] = "ctools"
projects[] = "colorbox"
projects[] = "ckeditor"
projects[] = "devel"
projects[] = "features"
projects[] = "globalredirect"
projects[] = "jquery_update"
projects[] = "l10n_update"
projects[] = "less"
projects[] = "libraries"
projects[] = "metatag"
projects[] = "module_filter"
projects[] = "navbar"
projects[] = "strongarm"
projects[] = "token"
projects[] = "views"
projects[] = "xmlsitemap"
; Themes
projects[] = "adminimal_theme"
projects[themes][type] = "theme"
projects[themes][download][type] = "git"
projects[themes][download][url] = "git://git.drupal.org/project/adminimal_theme.git"
projects[themes][download][branch] = "7.x-1.x" 

; Libraries

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backbone][download][type] = "file"
libraries[backbone][download][url] = "http://backbonejs.org/backbone-min.js"
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[lessphp][download][type] = "git"
libraries[lessphp][download][url] = "https://github.com/oyejorge/less.php.git"
libraries[lessphp][directory_name] = "lessphp"
libraries[lessphp][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[modernizr][download][type] = "file"
libraries[modernizr][download][url] = "http://stage.megatehniks.com/sites/all/libraries/modernizr/modernizr-min.js"
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[underscore][download][type] = "file"
libraries[underscore][download][url] = "http://stage.megatehniks.com/sites/all/libraries/underscore/underscore-min.js"
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"

